### ISSUE TITLE
S3 Box Update Error on ESPHome 2024.9.0

### ISSUE THREAD

**Issue by bradich** [esphome/wake-word-voice-assistants#22]
![Screenshot](https://github.com/user-attachments/assets/8018143d-147c-439b-9a2c-ee3f1e5b16c8)

Error:

INFO ESPHome 2024.9.0
INFO Reading configuration /config/esphome/esp32-s3-box-3-5ad0e0.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/5230/head
INFO Updating https://github.com/jesserockz/esphome-components.git@None
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

display.ili9xxx: [source /data/packages/dec89df9/esp32-s3-box-3/esp32-s3-box-3.yaml:688]
  
  'invert_colors' is a required option for [display.ili9xxx].
  platform: ili9xxx
  id: s3_box_lcd
  model: S3BOX
  data_rate: 40MHz
  cs_pin: 5
  dc_pin: 4
  reset_pin: 
    number: 48
    inverted: True
  update_interval: never
  pages: 
    - id: idle_page

**Comment by jesserockz** [comment]
This was fixed already by #19
